texts_collapse <- gsub("\\'", "", texts_collapse)
texts_collapse <- gsub("07\\)\\:", "(V):", texts_collapse)
texts_collapse <- gsub("\\(Krm\\:|\\(KrF\\s\\)", "(KrF):", texts_collapse)
texts_collapse <- gsub("\\(TD:|\\(T F\\)|\\(TF\\s\\)","(TF):", texts_collapse)
texts_collapse <- gsub("Odd Einar Dørum: Vi står faktisk", "Odd Einar Dørum (V): Vi står faktisk", texts_collapse)
texts_collapse <- gsub("GI\\):|\\(I\\-D\\:", "(H):", texts_collapse)
texts_collapse <- gsub("\\(SW:", "(SV):", texts_collapse)
texts_collapse <- gsub("W\\):|\\(W:", "(V):", texts_collapse)
texts_collapse <- gsub("Røsj orde", "Røsjorde", texts_collapse)
texts_collapse <- gsub("O\\(rF\\):", "(KrF):", texts_collapse)
texts_collapse <- gsub("Karin AndersentSV\\):", "Karin Andersent (SV):", texts_collapse)
texts_collapse <- gsub("Karin Kj ølmoen", "Karin Kjølmoen", texts_collapse)
texts_collapse <- gsub("Tore N ordtun", "Tore Nordtun", texts_collapse)
texts_collapse <- gsub("Ocomiteens", "(komiteens", texts_collapse)
texts_collapse <- gsub("F røiland", "Frøiland", texts_collapse)
texts_collapse <- gsub("Nesv ik", "Nesvik", texts_collapse)
texts_collapse <- gsub("Ev je", "Evje", texts_collapse)
texts_collapse <- gsub("Brø rby", "Brørby", texts_collapse)
texts_collapse <- gsub("Stråtv eit", "Stråtveit", texts_collapse)
texts_collapse <- gsub("Folk» ord", "Folkvord",texts_collapse)
texts_collapse <- gsub("\\(ordfører for saken\\)\\.", "(ordfører for saken):",texts_collapse)
texts_collapse <- gsub("Schj ett|Schj att|Schj øtt|Sch jøtt", "Schjøtt",texts_collapse)
texts_collapse <- gsub("J agland", "Jagland",texts_collapse)
texts_collapse <- gsub("Eirin F aldet", "Eirin Faldet",texts_collapse)
texts_collapse <- gsub("\\(frå salen\\)\\.", "(frå salen):",texts_collapse)
texts_collapse <- gsub("J ohanseu", "Johansen",texts_collapse)
texts_collapse <- gsub("Bj arne", "Bjarne",texts_collapse)
texts_collapse <- gsub("Godalzl", "Godal:",texts_collapse)
texts_collapse <- gsub("IIorn", "Horn",texts_collapse)
texts_collapse <- gsub("Sch jøtt", "Sch jøtt",texts_collapse)